### PR TITLE
Uses Merriweather for the editor font.

### PR DESCRIPTION
**Pull request by aerych**
Retains OpenSans for dialogs and other labels.

Needs Review: @bummytime

### CODE REVIEW

**Comment by bummytime** [comment]
@aerych Running the example app now and noticed the placeholder font for the title is Open Sans now:

screen shot 2015-06-16 at 7 41 02 pm

Is this by design?

**Comment by bummytime** [comment]
@aerych I wasn't really aware these changes were coming (@thianhlu maybe you did). Is the new all-Merriweather aesthetic our new standard now?

**Comment by aerych** [comment]
> noticed the placeholder font for the title is Open Sans now

Oops. Thanks for catching that. I'll get it sorted out. 

> Is the new all-Merriweather aesthetic our new standard now?

As far as content goes, that's my understanding.  @mnt can probably go into more detail.  I think if there's any doubt then let's hold off on this PR until everyone is on the same page!

**Comment by thianhlu** [comment]
I wasn't aware. @aerych Are you changing the reader to display Merriweather as well? If not, I'm not sure what prompted the change cause we would want to keep the two (display and creation) in sync. We initially had Merriweather in early mocks but we changed to open-sans because of the reader.

Also is this just simply a font swap or are you making adjustment so we keep similar x-heights and line-heights?

**Comment by aerych** [comment]
Hi @thianhlu.  Its part of the "calypsofication" work. We'll be using Merriweather for content areas including the reader. 

My thought for this patch was just a simple font swap. It didn't occur to me that x-heights and/or line-heights might also need an adjustment. Thanks for mentioning that!

**Comment by aerych** [comment]
Some screen shots of Merriweather in the demo app: https://cloudup.com/cEEqN_o5ZcE

**Comment by mnt** [comment]
The switch to Merriweather was proposed here: https://designomattic.wordpress.com/2015/04/21/the-more-the-merriweather/

And is being codified in updates to the pattern library here: https://designomattic.wordpress.com/2015/06/16/expanding-and-organizing-the-pattern-library/

The font size and line height should be determined by our pre-existing modular scale: https://wordpress.com/design-handbook/typography/

Specifically: 14px/21px for small screen devices and 16/24px for large screen devices.

screen shot 2015-06-16 at 5 45 08 pm

**Comment by bummytime** [comment]
Thanks for the info @mnt. @aerych it looks like we are defaulting the body text to 16px...do we need to change this to 14px?

**Comment by aerych** [comment]
@bummytime Yeppers!  We've been chatting about whether it made sense to use the smaller font and line sizes on the iPhone or always use the larger and possibly more legible sizes intended for the iPad.

**Comment by aerych** [comment]
Ready for round two @bummytime !!

**Comment by bummytime** [comment]
@aerych The visual side looks good. You may want to also increase the size of the HTML title/placeholder to match the latest updates:


https://cloudup.com/cJkrG0GYstJ

**Visual:**
screen shot 2015-06-17 at 7 32 03 pm

**HTML:**
screen shot 2015-06-17 at 7 32 13 pm

**Comment by aerych** [comment]
Huh... They *are* the same size for me.  iPhone 5s simulator iOS 8.3.  Which simulator + OS combo did you use? 


side-by-side

**Comment by aerych** [comment]
HTML *mode*.  Okay. On the same page now.  :tired_face:

The visual editor is so good I forgot all about the html source ;)

**Comment by aerych** [comment]
@bummytime third time's the charm?

**Comment by bummytime** [comment]
Word. :shipit:

**Comment by aerych** [comment]
Thanks Matt!

**Pull request merged**
