### PR TITLE
Simplifies paragraph wrapping

### LINKED ISSUE #842: Blockquote weirdness when adding images.
As reported by @SergioEstevao [in this video](https://cloudup.com/cuPtsI8nKcL).  This issue came up in [this PR](https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/841).

It seems like there's some oddity when adding images right before some blockquotes.  The text inside the blockquote is moved behind the image.  Check the video above for a demonstration of the issue.

### PR DESCRIPTION
**Pull request by diegoreymendez**
I was still seeing issues with #839. (EDIT: also fixes #842).

The code to wrap the current block of text in a paragraph was quite broken - this patch fixes it.

To test:
Just run the code, paste some text and blockquote it.  Make sure it works right.  Make sure it wraps the contents in a paragraph block.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
One issue that I detected, is that if you add three parapgrahs, then blokquote the middle one.
Then try to insert an image before the blockquote is pushed out of the text.

**Comment by SergioEstevao** [comment]
Blockquotes should apply to the full paragraph? or only to the selected text?

**Comment by diegoreymendez** [comment]
Regarding your second question, [blockquote applies to block elements](https://cloudup.com/cTZbTjvtRUQ) (not selection).  This was requested as-is back in the day.

**Comment by diegoreymendez** [comment]
> One issue that I detected, is that if you add three parapgrahs, then blokquote the middle one.  Then try to insert an image before the blockquote is pushed out of the text.

Can you provide more precise steps (or even better a video) showing the issue?  I tried repeating the steps provided but I didn't see any strange behaviour with the editor.

**Comment by SergioEstevao** [comment]
@diegoreymendez check this video: https://cldup.com/nKe99fYYij.mov

**Comment by diegoreymendez** [comment]
@SergioEstevao - Good catch.

However I could reproduce this in `develop` as well, meaning the issue is unrelated to the current changes.

I've created [a separate ticket for this bug](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/842).

**Comment by diegoreymendez** [comment]
@SergioEstevao - Added a fix to the image issue in this PR.  Check it out.

The ticket is #842.

**Comment by diegoreymendez** [comment]
You can test all these changes in WPiOS using branch `editor/integrate-latest`.

**Comment by SergioEstevao** [comment]
I tested this on the integration branch, and found some issues:

- If you add two paragraphs. Then insert a group of image in the middle of the two paragraphs. If you press delete all the images are deleted in one go
- If you cancel an image upload, by tapping on it and choose Cancel Upload the image next to it is canceled also.

**Comment by SergioEstevao** [comment]
@diegoreymendez I had a look on develop and it looks that both  issues already happens there, so I will investigate them in separate tickets.

**Comment by SergioEstevao** [comment]
:shipit:

**Pull request merged**
