### PR TITLE
Fix insertion of videos when they are the only content on the post

### LINKED ISSUE #797: Insertion of video on pages without any content fails
Expected behaviour:

- On a brand new post or one without any content.
- Click to insert media and select a video
- A video thumbnail should be show while the upload/progress is happening
- A video should be show on the end.

Actual behaviour:

-Nothing is show after selecting the video

How to Test:

- On the simulator you can drag and drop a video to the simulator to have a video in the Camera Roll
- The do the steps described on the Expected behaviour.
- Check also behaviour on post with content, by adding in the start, middle and end of the post.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #797 

Adds videos to the exception list when auto wrapping content.

See ticket for details what to tests.

Needs Review: @diegoreymendez

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Talked with @astralbodies - I'm reassigning to me since I'm free to tackle it.

**Comment by diegoreymendez** [comment]
@SergioEstevao - What's the iOS branch I can test this with?

**Comment by SergioEstevao** [comment]
@diegoreymendez: This can be tested on this branch issue/editor-798-test on the main app repo.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Check out [this video](https://cloudup.com/cPuc_OsUu5p).  The two big issues I'm seeing are:

- If the video is the first thing you add, you can't type before it.
- There's a caret coming up right in the middle of the video.

**Comment by diegoreymendez** [comment]
:shipit:

**Pull request merged**
