### PR TITLE
Bumps podspec version to 1.1.3.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Bumps podspec version to 1.1.3.

Also added myself and @SergioEstevao as authors.

Publishing to CocoaPods will be handled after this PR is approved.

/cc @bummytime for review.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
For the authors, shouldn't we use just Automattic mobile@automattic.com?

**Comment by diegoreymendez** [comment]
@SergioEstevao - I prefer to be listed there myself.

I do think we should all use the @automattic.com addresses, though.  Thoughts @bummytime?

**Comment by SergioEstevao** [comment]
For me it's just that if someones leaves Automattic that mail will stop existing, while the mobile@automattic should always be there.

**Comment by diegoreymendez** [comment]
Just added the mobile@automattic.com address on top.  Also switched all emails to @automattic.com since we're contributing through Automattic.

**Comment by SergioEstevao** [comment]
For me is ok then :) :shipit:

**Comment by diegoreymendez** [comment]
Reassigning since @SergioEstevao reviewed this.  Ty!

**Comment by bummytime** [comment]
Sorry for the late reply! Works for me! (late :shipit: :grinning: )

**Comment by diegoreymendez** [comment]
Ty @bummytime !

**Pull request merged**
