### PR TITLE
Migrates the editor to WKWebView.

### LINKED ISSUE #260: Switch to WKWebView instead of UIWebView
Title has it. This is an iOS 8 only api, but we could consider regressing to UIWebView for iOS 7 users.

Marketing blurb:

> WKWebView is the centerpiece of the modern WebKit API introduced in iOS 8 & OS X Yosemite. It replaces UIWebView in UIKit and WebView in AppKit, offering a consistent API across the two platforms.
> 
> Boasting responsive 60fps scrolling, built-in gestures, streamlined communication between app and webpage, and the same JavaScript engine as Safari, WKWebView is one of the most significant announcements to come out of WWDC 2014.

### PR DESCRIPTION
**Pull request by diegoreymendez**
Closes #260.

I'm marking this as "not ready" until we can do some proper testing.

Need some help testing this: @rachelmcr, @bummytime, @SergioEstevao.

**How to test:**
- WPiOS branch is `editor/260-wkwebview`.
- Run this editor alongside the old one and make sure there are no regressions.
- Bugs found in both the old editor and the new one should be ignored.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
For historical context: some of the code added in this PR was validated or taken from [this older PR](https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/753) by @SergioEstevao.

**Comment by bummytime** [comment]
Commented to @diegoreymendez offline about this, just commenting here for posterity...in the demo app, the format bar accessory view does not appear on the iPad Pro:

screen_shot_2016-02-05_at_11 14 40_am

**Comment by bummytime** [comment]
Also just as a followup, I am not seeing the iPad Pro format bar in the WPiOS tester branch either:

screen shot 2016-02-08 at 11 15 01 am

**Comment by diegoreymendez** [comment]
I'm closing this PR as there are limitations with `WKWebView` preventing the editor from fully working.

More specifically: there's no mechanism for setting cookies when attempting to download images.  Since some blogs are private, images need to have the necessary authentication cookies set.

More information can be found in #260.

**Pull request closed without merging**
