### PR TITLE
Log unhandled exceptions

### PR DESCRIPTION
**Pull request by diegoreymendez**
This PR adds logging of unhandled exceptions to our Javascript sources.  It also modularizes logging so that changes in `ZSSRichTextEditor` are unlikely to break error logging.  On top of that, it tries to make sure the new `WPHybridCallbacker` and `WPHybridLogger` classes are loaded, and an alert is thrown otherwise.

This PR also changes the default logging level to show errors.

**Test 1:**
- Randomly break `WPHybridCallbacker` and check that an alert is shown on startup.

**Test 2:**
- Randomly break `WPHybridLogger` and check that an alert is shown on startup.

**Test 3:**
- Randomly break `ZSSRichTextEditor` and eventually a log error should be shown depending on how the script was broken.
- For example: removing a method should show an exception with detailed information if that method is ever called.

### CODE REVIEW

**Comment by bummytime** [comment]
Hey @diegoreymendez I gave this a run through and looked over the code. The code looks fine but I had a few questions regarding general usage.  

* Tests 1 and 2 worked like a champ. I really like this and wonder if there is any value in using this to check for the proper loading of other scripts.
* The dialog that appears is obviously pretty noisy. Any thoughts on possibly disabling this on app store builds as a precaution? screen shot 2015-04-16 at 9 04 14 am
* Test 3 worked great. So helpful now.

**Comment by diegoreymendez** [comment]
As discussed over Slack, the dialog should be ok even on release builds, as the editor should be terribly broken to show that message and it would at least offer us better user feedback if that ever happened.

**Comment by bummytime** [comment]
:shipit:

**Pull request merged**
