### PR TITLE
Replace Open Sans with system fonts

### PR DESCRIPTION
**Pull request by koke**
See: wordpress-mobile/WordPress-iOS#4895
Cc: @mattmiklic 
Needs Review: @bummytime

### CODE REVIEW

**Comment by mattmiklic** [comment]
Everything is looking good to me here so far in a quick overview; will continue to test in real-world use.

**Comment by bummytime** [comment]
@koke if @mattmiklic is happy, I am happy. :-) Seriously, everything looks ok form my perspective, so if y'all are good with it :shipit:

**Comment by SergioEstevao** [comment]
@mattmiklic the only question that I have here, is that on the images and videos when an upload fails we where showing a message saying "failed because of ....", and after an upload is done we where showing a "Edit" text when tapping on the image. both of these where using Open San and now they where replaced for the system font (SF) should we use that or Merriweather.

**Comment by mattmiklic** [comment]
@SergioEstevao Both of those should be in system fonts. Thanks for checking!

**Pull request merged**
