### PR TITLE
Links inserted from scratch leave the selection at the end of the link.

### LINKED ISSUE #722: Link Modal - Improving UX
After inserting a link, linked word(s) remain selected by editor. We should be losing focus on that word and have the cursor directly to the right of the word after linking.

current:

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes #722.

**Test 1:**
1. Launch the demo app.
2. Start writing
3. Insert a link from scratch.
4. After inserting the link the selection should be placed at the end of the link.

**Test 2:**
1. Launch the demo app.
2. Select an existing word to add a link to it.
3. Insert a link.
4. After inserting the link the selection should still be surrounding the full word.

/cc @bummytime

### CODE REVIEW

**Comment by bummytime** [comment]
Works as expected and code is square @diegoreymendez. As I was testing it, I was wondering about what you said in https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/722#issuecomment-184792626

> However if the user double taps on an existing word to add a link, closing the dialogue should probably maintain the previous selection. Thoughts?

Could be a personal preference but in using this fix, it felt like the selection should always be dismissed and cursor placed right after the link. For grins I looked at what the web did when creating links with selected text and they dismiss the selection too. ¯\_(ツ)_/¯

I could go either way tbh. Perhaps @rachelmcr has some strong opinions.

maxell

**Comment by diegoreymendez** [comment]
@bummytime - Thank you for the feedback.  I don't feel too strongly about this but would like to know what @rachelmcr thinks, as well, before proceeding.

**Comment by rachelmcr** [comment]
I agree with @bummytime — I would expect the selection to always be dismissed (the same as in the web editor) after I finish adding a link, even when I explicitly select the text before adding the link.

I don't feel super strongly about it, either, but given that the web does it that way, I'd argue for consistency based on that at least (unless there's a compelling reason why an app user might expect different behavior).

**Comment by diegoreymendez** [comment]
Thanks guys.  Changes applied!  Let me know if this is good to go.

**Comment by bummytime** [comment]
Looks good @diegoreymendez :shipit:

**Comment by diegoreymendez** [comment]
Ty!

**Pull request merged**
