### PR TITLE
The ZSSField callbacker does not directly reference the editor's callback method anymore.

### PR DESCRIPTION
**Pull request by diegoreymendez**
This is the first PR in a series of upcoming PRs to abstract `ZSSField` from `ZSSEditor`.  The idea behind these changes it to make the code more modular and eventually easier to maintain and unit-test (yep, planning to add unit-tests for our editor!).

`ZSSField` was executing callbacks by directly referencing `ZSSEditor.callback()`.  This was bad design-wise because it meant the classes were highly tied to one another (thus making it very hard to instantiate `ZSSField` without `ZSSEditor` to unit test it).

**How to test:**
- Increate the app's logging level to ALL in `WPEditorLoggingConfiguration.m`.
- Run the app.
- Edit the fields, change selections, etc.
- Make sure field-delivered callbacks are still received by the app.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
@bummytime - Please don't merge this yet, as this was branched from [this pending PR](https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/622).

**Comment by diegoreymendez** [comment]
@bummytime - This is now ready to review.  All the unnecessary changes were removed.

**Comment by diegoreymendez** [comment]
Also /cc @SergioEstevao.

**Comment by bummytime** [comment]
Looks like a nice little improvement @diegoreymendez. :shipit:

**Comment by SergioEstevao** [comment]
Please don't merge this just now, need to test it with videos and photos insertion.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Let me know.

**Comment by SergioEstevao** [comment]
@diegoreymendez, at the moment it's working but looking at the code I see you didn't the invocation in the two place where I was worried about it. There are:

ZSSField.prototype.sendImageTappedCallback

ZSSField.prototype.sendVideoTappedCallback

the main issue that I found out when doing this is that when calling ZSSField callback we add a parameter to the callback URL called id to identify the field being changed. This was conflicting with the id parameter of these callbacks.

Looking back this was error on the implementation of these methods instead of using id, they need to change to use something called mediaID. 

If you want after you merge this in I can do the necessary changes on the editor to make this work properly.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Good points... I think at this time the best is to treat the changes you mention separately - they're related but it'll be easier for us to review the code by splitting it.  Let me know when it's ready and I can help you reviewing it.

**Pull request merged**
