### PR TITLE
wp-admin parity

### LINKED ISSUE #503: Standardize <p> tags when open post drafted from wp-admin
Make sure we are properly handling paragraphs created in WP-admin Text mode. The HTML that is saved down should provide us with the proper `<p>` to render in our Mobile editor (visual & html)

Posts generated on WP-admin (web). 
- Add a post that has a line breaks (pressing return). 
- On WP-admin, the UI creates a `<p>` which also maps to Visual Mode. 
- If you open this same post on Mobile-editor, it does not display the line break on our visual/default mode but it does on the HTML mode. 
- Sadly it does not display the `<p>` either.

### PR DESCRIPTION
**Pull request by bummytime**
This PR should fix #503 and #500 (which are included in #501). In addition, it helps #502 a lot as well.

The goal of this PR was to make the mobile editor behave like more wp-admin. This means doing things like removing `<p/>` tags and inserting `\n\n` when in HTML mode and then reinserting `<p/>` when in visual mode.  These changes, while not ideal, provide a consistent user experience between web and native mobile. 

The bulk of this work was achieved by using the exact same scripts wp-admin uses in `wp-admin/js/editor.js`. They are now called anytime text is fetched or pushed into the editor. In addition, to fix a placeholder issue a new `setText()` method was added to `WPEditorField` that allows the caller to insert plain, non-HTML text into the field.

If you want to give this bad boy a ride in WPiOS, use this branch: https://github.com/wordpress-mobile/WordPress-iOS/tree/issue/editor-501-wp-admin-parity

/cc @diegoreymendez would you mind reviewing... :grinning:

### CODE REVIEW

**Comment by bummytime** [comment]
I should mention that I did change the functions in `Assets/wpsave.js` and `Assets/wpload.js` a little bit. I added comments and a null check at the top of each function (in order to fix some bugs I was seeing in the editor).

**Comment by diegoreymendez** [comment]
I'm on this right now... sorry for the delay @bummytime

**Comment by bummytime** [comment]
awesome @diegoreymendez !

**Comment by diegoreymendez** [comment]
:shipit:

**Comment by diegoreymendez** [comment]
:shipit:

**Pull request merged**
